# Generated by Django 5.0.2 on 2024-02-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0003_alter_usuario_idade_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(max_length=255),
        ),
    ]
