# Generated by Django 5.0.2 on 2024-02-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0004_alter_usuario_idade_alter_usuario_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.TextField(default='', max_length=11),
        ),
    ]
