# Generated by Django 5.0.2 on 2024-02-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_user', '0005_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.TextField(max_length=11, unique=True),
        ),
    ]
